---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  enable:
    - lll
    - testifylint
  disable:
    - unused
  exclusions:
    generated: strict
    rules:
      - linters:
          - lll
        path: ^(internal/delivery/http/handler|cmd/)\w*\.go$
  settings:
    testifylint:
      enable-all: true
    lll:
      tab-width: 8
      line-length: 180
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: backend
  exclusions:
    generated: strict
    paths:
      - docs/docs.go
run:
  build-tags:
    - integration
