// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend/config"
	"backend/internal/client"
	"backend/internal/delivery/http"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) *http.Server {
	engine := client.NewGin()
	articleHandlerImpl := http.ProvideArticleHandler()
	bookHandlerImpl := http.ProvideBookHandler()
	cartHandlerImpl := http.ProvideCartHandler()
	categoryHandlerImpl := http.ProvideCategoryHandler()
	mediaHandlerImpl := http.ProvideMediaHandler()
	orderHandlerImpl := http.ProvideOrderHandler()
	routerImpl := http.ProvideRouter(articleHandlerImpl, bookHandlerImpl, cartHandlerImpl, categoryHandlerImpl, mediaHandlerImpl, orderHandlerImpl)
	server := config.NewServer()
	authHandlerImpl := http.ProvideAuthHandler(server)
	httpServer := http.NewServer(engine, routerImpl, server, authHandlerImpl)
	return httpServer
}

// wire.go:

var ConfigSet = wire.NewSet(config.NewServer)

var HandlerSet = wire.NewSet(http.ProvideArticleHandler, wire.Bind(
	new(http.ArticleHandler),
	new(*http.ArticleHandlerImpl),
), http.ProvideBookHandler, wire.Bind(
	new(http.BookHandler),
	new(*http.BookHandlerImpl),
), http.ProvideCartHandler, wire.Bind(
	new(http.CartHandler),
	new(*http.CartHandlerImpl),
), http.ProvideCategoryHandler, wire.Bind(
	new(http.CategoryHandler),
	new(*http.CategoryHandlerImpl),
), http.ProvideMediaHandler, wire.Bind(
	new(http.MediaHandler),
	new(*http.MediaHandlerImpl),
), http.ProvideOrderHandler, wire.Bind(
	new(http.OrderHandler),
	new(*http.OrderHandlerImpl),
), http.ProvideAuthHandler, wire.Bind(
	new(http.AuthHandler),
	new(*http.AuthHandlerImpl),
),
)

var RouterSet = wire.NewSet(http.ProvideRouter, wire.Bind(
	new(http.Router),
	new(*http.RouterImpl),
),
)

var ClientSet = wire.NewSet(client.NewGin)
