// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend/config"
	"backend/internal/application"
	"backend/internal/client"
	"backend/internal/delivery/http"
	"backend/internal/domain"
	"backend/internal/infrastructure/objectstorages3"
	"backend/internal/infrastructure/paymentservice"
	"backend/internal/infrastructure/repositorypostgres"
	"backend/internal/service"
	"backend/pkg/logger"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) *http.Server {
	engine := client.NewGin()
	server := config.NewServer()
	pool := client.NewDBConnection(ctx, server)
	queries := client.NewDBQueries(pool)
	book := repositorypostgres.ProvideBook(queries, pool)
	validate := client.NewValidate()
	serviceBook := service.ProvideBook(validate)
	category := repositorypostgres.ProvideCategory(queries, pool)
	serviceCategory := service.ProvideCategory(validate)
	media := repositorypostgres.ProvideMedia(queries, pool)
	serviceMedia := service.ProvideMedia(validate)
	applicationBook := application.ProvideBook(book, serviceBook, category, serviceCategory, media, serviceMedia)
	bookHandlerImpl := http.ProvideBookHandler(applicationBook)
	cart := repositorypostgres.ProvideCart(queries, pool)
	serviceCart := service.ProvideCart(validate)
	applicationCart := application.ProvideCart(cart, serviceCart, book, serviceBook)
	cartHandlerImpl := http.ProvideCartHandler(applicationCart)
	applicationCategory := application.ProvideCategory(category, serviceCategory)
	categoryHandlerImpl := http.ProvideCategoryHandler(applicationCategory)
	s3Client := client.NewS3(ctx, server)
	presignClient := client.NewS3Presign(s3Client)
	objectstorages3Media := objectstorages3.ProvideMedia(s3Client, presignClient, server)
	applicationMedia := application.ProvideMedia(media, serviceMedia, objectstorages3Media)
	mediaHandlerImpl := http.ProvideMediaHandler(applicationMedia)
	order := repositorypostgres.ProvideOrder(queries, pool)
	serviceOrder := service.ProvideOrder(validate)
	vnPay := paymentservice.ProvideVNPay(server)
	applicationOrder := application.ProvideOrder(order, serviceOrder, book, serviceBook, cart, vnPay)
	orderHandlerImpl := http.ProvideOrderHandler(applicationOrder)
	goCloak := client.NewKeycloak(ctx, server)
	authMiddlewareImpl := http.ProvideAuthMiddleware(goCloak, server)
	loggerConfig := logger.NewConfig(server)
	zapLogger := logger.New(loggerConfig)
	loggingMiddlewareImpl := http.ProvideLoggingMiddleware(zapLogger)
	metricMiddlewareImpl := http.ProvideMetricMiddleware()
	roleMiddlewareImpl := http.ProvideRoleMiddleware(server)
	routerImpl := http.ProvideRouter(bookHandlerImpl, cartHandlerImpl, categoryHandlerImpl, mediaHandlerImpl, orderHandlerImpl, authMiddlewareImpl, loggingMiddlewareImpl, metricMiddlewareImpl, roleMiddlewareImpl)
	authHandlerImpl := http.ProvideAuthHandler(server)
	httpServer := http.NewServer(engine, routerImpl, server, authHandlerImpl)
	return httpServer
}

// wire.go:

var ConfigSet = wire.NewSet(config.NewServer, logger.NewConfig)

var LoggerSet = wire.NewSet(logger.New)

var DbSet = wire.NewSet(client.NewDBConnection, client.NewDBQueries, client.NewDBTransactor)

var ObjectStorageSet = wire.NewSet(objectstorages3.ProvideMedia, wire.Bind(
	new(application.MediaObjectStorage),
	new(*objectstorages3.Media),
),
)

var ServiceSet = wire.NewSet(service.ProvideBook, wire.Bind(
	new(domain.BookService),
	new(*service.Book),
), service.ProvideCategory, wire.Bind(
	new(domain.CategoryService),
	new(*service.Category),
), service.ProvideCart, wire.Bind(
	new(domain.CartService),
	new(*service.Cart),
), service.ProvideOrder, wire.Bind(
	new(domain.OrderService),
	new(*service.Order),
), service.ProvideMedia, wire.Bind(
	new(domain.MediaService),
	new(*service.Media),
),
)

var RepositorySet = wire.NewSet(repositorypostgres.ProvideCategory, wire.Bind(
	new(domain.CategoryRepository),
	new(*repositorypostgres.Category),
), repositorypostgres.ProvideBook, wire.Bind(
	new(domain.BookRepository),
	new(*repositorypostgres.Book),
), repositorypostgres.ProvideCart, wire.Bind(
	new(domain.CartRepository),
	new(*repositorypostgres.Cart),
), repositorypostgres.ProvideOrder, wire.Bind(
	new(domain.OrderRepository),
	new(*repositorypostgres.Order),
), repositorypostgres.ProvideMedia, wire.Bind(
	new(domain.MediaRepository),
	new(*repositorypostgres.Media),
),
)

var ApplicationSet = wire.NewSet(application.ProvideBook, wire.Bind(
	new(http.BookApplication),
	new(*application.Book),
), application.ProvideCategory, wire.Bind(
	new(http.CategoryApplication),
	new(*application.Category),
), application.ProvideCart, wire.Bind(
	new(http.CartApplication),
	new(*application.Cart),
), application.ProvideOrder, wire.Bind(
	new(http.OrderApplication),
	new(*application.Order),
), application.ProvideMedia, wire.Bind(
	new(http.MediaApplication),
	new(*application.Media),
),
)

var HandlerSet = wire.NewSet(http.ProvideBookHandler, wire.Bind(
	new(http.BookHandler),
	new(*http.BookHandlerImpl),
), http.ProvideCartHandler, wire.Bind(
	new(http.CartHandler),
	new(*http.CartHandlerImpl),
), http.ProvideCategoryHandler, wire.Bind(
	new(http.CategoryHandler),
	new(*http.CategoryHandlerImpl),
), http.ProvideMediaHandler, wire.Bind(
	new(http.MediaHandler),
	new(*http.MediaHandlerImpl),
), http.ProvideOrderHandler, wire.Bind(
	new(http.OrderHandler),
	new(*http.OrderHandlerImpl),
), http.ProvideAuthHandler, wire.Bind(
	new(http.AuthHandler),
	new(*http.AuthHandlerImpl),
),
)

var MiddlewareSet = wire.NewSet(http.ProvideAuthMiddleware, wire.Bind(
	new(http.AuthMiddleware),
	new(*http.AuthMiddlewareImpl),
), http.ProvideLoggingMiddleware, wire.Bind(
	new(http.LoggingMiddleware),
	new(*http.LoggingMiddlewareImpl),
), http.ProvideMetricMiddleware, wire.Bind(
	new(http.MetricMiddleware),
	new(*http.MetricMiddlewareImpl),
), http.ProvideRoleMiddleware, wire.Bind(
	new(http.RoleMiddleware),
	new(*http.RoleMiddlewareImpl),
),
)

var RouterSet = wire.NewSet(http.ProvideRouter, wire.Bind(
	new(http.Router),
	new(*http.RouterImpl),
),
)

var ClientSet = wire.NewSet(client.NewGin, client.NewValidate, client.NewS3, client.NewS3Presign, client.NewKeycloak)

var PaymentServiceSet = wire.NewSet(paymentservice.ProvideVNPay, wire.Bind(
	new(application.OrderPaymentService),
	new(*paymentservice.VNPay),
),
)
