CREATE TABLE media (
  id UUID PRIMARY KEY,
  url TEXT NOT NULL,
  alt_text TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  book_id UUID REFERENCES books (id) ON UPDATE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE categories (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE books (
  id UUID PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  author TEXT NOT NULL,
  price DECIMAL(12, 0) NOT NULL,
  pages_count INTEGER NOT NULL,
  year_published INTEGER NOT NULL,
  publisher TEXT NOT NULL,
  weight DECIMAL,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  purchase_count INTEGER NOT NULL DEFAULT 0,
  rating REAL NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE books_media (
  book_id UUID NOT NULL REFERENCES books (id) ON UPDATE CASCADE,
  media_id UUID NOT NULL REFERENCES media (id) ON UPDATE CASCADE,
  is_cover BOOLEAN NOT NULL,
  PRIMARY KEY (book_id, media_id)
);

CREATE TABLE books_categories (
  book_id UUID NOT NULL REFERENCES books (id) ON UPDATE CASCADE,
  category_id UUID NOT NULL REFERENCES categories (id) ON UPDATE CASCADE,
  PRIMARY KEY (book_id, category_id)
);

CREATE TABLE reviews (
  id UUID PRIMARY KEY,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  vote_count INTEGER NOT NULL DEFAULT 0,
  content TEXT,
  user_id UUID NOT NULL,
  book_id UUID NOT NULL REFERENCES books (id) ON UPDATE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE review_votes (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  review_id UUID NOT NULL REFERENCES reviews (id) ON UPDATE CASCADE,
  is_up BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE articles (
  id UUID PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  thumbnail_id UUID REFERENCES media (id) ON UPDATE CASCADE,
  content TEXT NOT NULL,
  tags TEXT[],
  user_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE carts (
  id UUID PRIMARY KEY,
  user_id UUID UNIQUE NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cart_items (
  id UUID PRIMARY KEY,
  quantity INTEGER NOT NULL DEFAULT 1,
  cart_id UUID NOT NULL REFERENCES carts (id) ON UPDATE CASCADE,
  book_id UUID NOT NULL REFERENCES books (id) ON UPDATE CASCADE
);

CREATE TABLE order_statuses (
  id UUID PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE order_providers (
  id UUID PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE orders (
  id UUID PRIMARY KEY,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total_amount DECIMAL(12, 0) NOT NULL,
  is_paid BOOLEAN NOT NULL DEFAULT FALSE,
  user_id UUID NOT NULL,
  status_id UUID NOT NULL REFERENCES order_statuses (id) ON UPDATE CASCADE,
  provider_id UUID NOT NULL REFERENCES order_providers (id) ON UPDATE CASCADE
);

CREATE TABLE order_items (
  id UUID PRIMARY KEY,
  quantity INTEGER NOT NULL,
  order_id UUID NOT NULL REFERENCES orders (id) ON UPDATE CASCADE,
  price DECIMAL(12, 0) NOT NULL,
  book_id UUID NOT NULL REFERENCES books (id) ON UPDATE CASCADE
);

INSERT INTO order_providers (id, name) VALUES
('00000000-0000-7000-0000-000000000001', 'COD'),
('00000000-0000-7000-0000-000000000002', 'VNPAY'),
('00000000-0000-7000-0000-000000000003', 'MOMO'),
('00000000-0000-7000-0000-000000000004', 'ZALOPAY')
ON CONFLICT (id) DO NOTHING;

INSERT INTO order_statuses (id, name) VALUES
('00000000-0000-7000-0000-000000000001', 'Pending'),
('00000000-0000-7000-0000-000000000002', 'Processing'),
('00000000-0000-7000-0000-000000000003', 'Shipped'),
('00000000-0000-7000-0000-000000000004', 'Delivered'),
('00000000-0000-7000-0000-000000000005', 'Cancelled')
ON CONFLICT (id) DO NOTHING;
