// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTempTableCartItems = `-- name: CreateTempTableCartItems :exec
CREATE TEMPORARY TABLE temp_cart_items (
  id UUID PRIMARY KEY,
  quantity INTEGER NOT NULL,
  cart_id UUID NOT NULL,
  book_id UUID NOT NULL
) ON COMMIT DROP
`

func (q *Queries) CreateTempTableCartItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTempTableCartItems)
	return err
}

const getCart = `-- name: GetCart :one
SELECT
  id, user_id, updated_at
FROM
  carts
WHERE
  CASE
    WHEN $1::uuid IS NULL THEN TRUE
    WHEN $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE id = $1::uuid
  END
  AND CASE
    WHEN $2::uuid IS NULL THEN TRUE
    WHEN $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE user_id = $2::uuid
  END
`

type GetCartParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCart(ctx context.Context, arg GetCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, arg.ID, arg.UserID)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.UpdatedAt)
	return i, err
}

type InsertTempTableCartItemsParams struct {
	ID       uuid.UUID
	Quantity int32
	CartID   uuid.UUID
	BookID   uuid.UUID
}

const listCartItems = `-- name: ListCartItems :many
SELECT
  id, quantity, cart_id, book_id
FROM
  cart_items
WHERE
  CASE
    WHEN $1::uuid IS NULL THEN TRUE
    WHEN $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE cart_id = $1::uuid
  END
`

type ListCartItemsParams struct {
	CartID uuid.UUID
}

func (q *Queries) ListCartItems(ctx context.Context, arg ListCartItemsParams) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, arg.CartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.CartID,
			&i.BookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeCartItemsFromTemp = `-- name: MergeCartItemsFromTemp :exec
MERGE INTO cart_items AS target
USING temp_cart_items AS source
  ON target.id = source.id
WHEN MATCHED THEN
  UPDATE SET
    quantity = source.quantity,
    cart_id = source.cart_id,
    book_id = source.book_id
WHEN NOT MATCHED THEN
  INSERT (
    id,
    quantity,
    cart_id,
    book_id
  )
  VALUES (
    source.id,
    source.quantity,
    source.cart_id,
    source.book_id
  )
WHEN NOT MATCHED BY SOURCE
  AND target.cart_id IN (SELECT DISTINCT cart_id FROM temp_cart_items) THEN
  DELETE
`

func (q *Queries) MergeCartItemsFromTemp(ctx context.Context) error {
	_, err := q.db.Exec(ctx, mergeCartItemsFromTemp)
	return err
}

const upsertCart = `-- name: UpsertCart :exec
INSERT INTO carts (
  id,
  user_id,
  updated_at
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  updated_at = EXCLUDED.updated_at
`

type UpsertCartParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertCart(ctx context.Context, arg UpsertCartParams) error {
	_, err := q.db.Exec(ctx, upsertCart, arg.ID, arg.UserID, arg.UpdatedAt)
	return err
}
