// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT
  COUNT(*) AS count
FROM
  categories
WHERE
  CASE
    WHEN $1::text = 'exclude' THEN deleted_at IS NULL
    WHEN $1::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $1::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
`

type CountCategoriesParams struct {
	Deleted string
}

func (q *Queries) CountCategories(ctx context.Context, arg CountCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, arg.Deleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategory = `-- name: GetCategory :one
SELECT
  id, slug, name, description, created_at, updated_at, deleted_at
FROM
  categories
WHERE
  CASE
    WHEN $1::uuid IS NULL THEN TRUE
    WHEN $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE id = $1::uuid
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    WHEN $2::text = '' THEN TRUE
    ELSE slug = $2::text
  END
  AND CASE
    WHEN $3::text = 'exclude' THEN deleted_at IS NULL
    WHEN $3::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $3::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
`

type GetCategoryParams struct {
	ID      uuid.UUID
	Slug    string
	Deleted string
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.Slug, arg.Deleted)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
  id, slug, name, description, created_at, updated_at, deleted_at
FROM
  categories
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::text = '' THEN TRUE
    ELSE (
      name ||| ($2::text)
      AND description ||| ($2::text)
    )
  END
  AND CASE
    WHEN $3::text = 'exclude' THEN deleted_at IS NULL
    WHEN $3::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $3::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
ORDER BY
  CASE WHEN
    $2::text <> '' THEN pdb.score(id)
  END DESC,
  id DESC
OFFSET $4::integer
LIMIT NULLIF($5::integer, 0)
`

type ListCategoriesParams struct {
	IDs     []uuid.UUID
	Search  string
	Deleted string
	Offset  int32
	Limit   int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.IDs,
		arg.Search,
		arg.Deleted,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategory = `-- name: UpsertCategory :exec
INSERT INTO categories (
  id,
  slug,
  name,
  description,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  NULLIF($7::timestamptz, '0001-01-01T00:00:00Z'::timestamptz)
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at,
  deleted_at = COALESCE(EXCLUDED.deleted_at, categories.deleted_at)
`

type UpsertCategoryParams struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCategory,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
