// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertTempTableBooksCategories implements pgx.CopyFromSource.
type iteratorForInsertTempTableBooksCategories struct {
	rows                 []InsertTempTableBooksCategoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTempTableBooksCategories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTempTableBooksCategories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookID,
		r.rows[0].CategoryID,
	}, nil
}

func (r iteratorForInsertTempTableBooksCategories) Err() error {
	return nil
}

func (q *Queries) InsertTempTableBooksCategories(ctx context.Context, arg []InsertTempTableBooksCategoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"temp_books_categories"}, []string{"book_id", "category_id"}, &iteratorForInsertTempTableBooksCategories{rows: arg})
}

// iteratorForInsertTempTableBooksMedium implements pgx.CopyFromSource.
type iteratorForInsertTempTableBooksMedium struct {
	rows                 []InsertTempTableBooksMediumParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTempTableBooksMedium) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTempTableBooksMedium) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookID,
		r.rows[0].MediaID,
		r.rows[0].Order,
		r.rows[0].IsCover,
	}, nil
}

func (r iteratorForInsertTempTableBooksMedium) Err() error {
	return nil
}

func (q *Queries) InsertTempTableBooksMedium(ctx context.Context, arg []InsertTempTableBooksMediumParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"temp_books_medium"}, []string{"book_id", "media_id", "order", "is_cover"}, &iteratorForInsertTempTableBooksMedium{rows: arg})
}

// iteratorForInsertTempTableCartItems implements pgx.CopyFromSource.
type iteratorForInsertTempTableCartItems struct {
	rows                 []InsertTempTableCartItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTempTableCartItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTempTableCartItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Quantity,
		r.rows[0].CartID,
		r.rows[0].BookID,
	}, nil
}

func (r iteratorForInsertTempTableCartItems) Err() error {
	return nil
}

func (q *Queries) InsertTempTableCartItems(ctx context.Context, arg []InsertTempTableCartItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"temp_cart_items"}, []string{"id", "quantity", "cart_id", "book_id"}, &iteratorForInsertTempTableCartItems{rows: arg})
}

// iteratorForInsertTempTableOrderItems implements pgx.CopyFromSource.
type iteratorForInsertTempTableOrderItems struct {
	rows                 []InsertTempTableOrderItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTempTableOrderItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTempTableOrderItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Quantity,
		r.rows[0].OrderID,
		r.rows[0].Price,
		r.rows[0].BookID,
	}, nil
}

func (r iteratorForInsertTempTableOrderItems) Err() error {
	return nil
}

func (q *Queries) InsertTempTableOrderItems(ctx context.Context, arg []InsertTempTableOrderItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"temp_order_items"}, []string{"id", "quantity", "order_id", "price", "book_id"}, &iteratorForInsertTempTableOrderItems{rows: arg})
}
