// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMedia = `-- name: GetMedia :one
SELECT
  id, url, alt_text, "order", book_id, created_at, deleted_at
FROM
  media
WHERE
  id = $1
  AND CASE
    WHEN $2::text = 'exclude' THEN deleted_at IS NULL
    WHEN $2::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $2::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
`

type GetMediaParams struct {
	ID      uuid.UUID
	Deleted string
}

func (q *Queries) GetMedia(ctx context.Context, arg GetMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, arg.ID, arg.Deleted)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.AltText,
		&i.Order,
		&i.BookID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT
  id, url, alt_text, "order", book_id, created_at, deleted_at
FROM
  media
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    WHEN cardinality($2::uuid[]) = 0 THEN TRUE
    ELSE book_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::text = 'exclude' THEN deleted_at IS NULL
    WHEN $3::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $3::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
ORDER BY
  book_id ASC,
  "order" ASC,
  id ASC
`

type ListMediaParams struct {
	IDs     []uuid.UUID
	BookIds []uuid.UUID
	Deleted string
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.IDs, arg.BookIds, arg.Deleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.AltText,
			&i.Order,
			&i.BookID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMedia = `-- name: UpsertMedia :exec
INSERT INTO media (
  id,
  url,
  alt_text,
  "order",
  book_id,
  created_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  NULLIF($7::timestamptz, '0001-01-01T00:00:00Z'::timestamptz)
)
ON CONFLICT (id) DO UPDATE SET
  url = EXCLUDED.url,
  alt_text = EXCLUDED.alt_text,
  "order" = EXCLUDED."order",
  book_id = EXCLUDED.book_id,
  created_at = EXCLUDED.created_at,
  deleted_at = COALESCE(EXCLUDED.deleted_at, media.deleted_at)
`

type UpsertMediaParams struct {
	ID        uuid.UUID
	URL       string
	AltText   *string
	Order     int32
	BookID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) error {
	_, err := q.db.Exec(ctx, upsertMedia,
		arg.ID,
		arg.URL,
		arg.AltText,
		arg.Order,
		arg.BookID,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}
