// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          uuid.UUID
	Slug        string
	Title       string
	ThumbnailID pgtype.UUID
	Content     string
	Tags        []string
	UserID      uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Book struct {
	ID            uuid.UUID
	Title         string
	Description   *string
	Author        string
	Price         pgtype.Numeric
	PagesCount    int32
	Year          int32
	Publisher     string
	Weight        pgtype.Numeric
	StockQuantity int32
	PurchaseCount int32
	Rating        float32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type BooksCategory struct {
	BookID     uuid.UUID
	CategoryID uuid.UUID
}

type BooksMedium struct {
	BookID  uuid.UUID
	MediaID uuid.UUID
	Order   int32
	IsCover bool
}

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID       uuid.UUID
	Quantity int32
	CartID   uuid.UUID
	BookID   uuid.UUID
}

type Category struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Medium struct {
	ID        uuid.UUID
	URL       string
	AltText   *string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Order struct {
	ID          uuid.UUID
	Address     string
	City        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TotalAmount pgtype.Numeric
	IsPaid      bool
	UserID      uuid.UUID
	StatusID    uuid.UUID
	ProviderID  uuid.UUID
}

type OrderItem struct {
	ID       uuid.UUID
	Quantity int32
	OrderID  uuid.UUID
	Price    pgtype.Numeric
	BookID   uuid.UUID
}

type OrderProvider struct {
	ID   uuid.UUID
	Name string
}

type OrderStatus struct {
	ID   uuid.UUID
	Name string
}

type Review struct {
	ID        uuid.UUID
	Rating    int16
	VoteCount int32
	Content   *string
	UserID    uuid.UUID
	BookID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ReviewVote struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ReviewID  uuid.UUID
	IsUp      bool
	CreatedAt pgtype.Timestamptz
}

type TempBooksCategory struct {
	BookID     uuid.UUID
	CategoryID uuid.UUID
}

type TempBooksMedium struct {
	BookID  uuid.UUID
	MediaID uuid.UUID
	Order   int32
	IsCover bool
}

type TempCartItem struct {
	ID       uuid.UUID
	Quantity int32
	CartID   uuid.UUID
	BookID   uuid.UUID
}

type TempOrderItem struct {
	ID       uuid.UUID
	Quantity int32
	OrderID  uuid.UUID
	Price    pgtype.Numeric
	BookID   uuid.UUID
}
