// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT
  COUNT(*) AS count
FROM
  orders
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    WHEN cardinality($2::uuid[]) = 0 THEN TRUE
    ELSE user_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    WHEN cardinality($3::uuid[]) = 0 THEN TRUE
    ELSE status_id = ANY ($3::uuid[])
  END
`

type CountOrdersParams struct {
	IDs       []uuid.UUID
	UserIDs   []uuid.UUID
	StatusIDs []uuid.UUID
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.IDs, arg.UserIDs, arg.StatusIDs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTempTableOrderItems = `-- name: CreateTempTableOrderItems :exec
CREATE TEMPORARY TABLE temp_order_items (
  id UUID PRIMARY KEY,
  quantity INTEGER NOT NULL,
  order_id UUID NOT NULL,
  price DECIMAL(12, 0) NOT NULL,
  book_id UUID NOT NULL
) ON COMMIT DROP
`

func (q *Queries) CreateTempTableOrderItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTempTableOrderItems)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT
  id, address, city, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
FROM
  orders
WHERE
  id = $1
`

type GetOrderParams struct {
	ID uuid.UUID
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalAmount,
		&i.IsPaid,
		&i.UserID,
		&i.StatusID,
		&i.ProviderID,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT
  id, quantity, order_id, price, book_id
FROM
  order_items
WHERE
  id = $1
`

type GetOrderItemParams struct {
	ID uuid.UUID
}

func (q *Queries) GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, arg.ID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.OrderID,
		&i.Price,
		&i.BookID,
	)
	return i, err
}

const getOrderProvider = `-- name: GetOrderProvider :one
SELECT
  id, name
FROM
  order_providers
WHERE
  CASE
    WHEN $1::uuid IS NULL THEN TRUE
    WHEN $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE id = $1::uuid
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    WHEN $2::text = '' THEN TRUE
    ELSE name = $2::text
  END
`

type GetOrderProviderParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetOrderProvider(ctx context.Context, arg GetOrderProviderParams) (OrderProvider, error) {
	row := q.db.QueryRow(ctx, getOrderProvider, arg.ID, arg.Name)
	var i OrderProvider
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT
  id, name
FROM
  order_statuses
WHERE
  CASE
    WHEN $1::uuid IS NULL THEN TRUE
    WHEN $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE id = $1::uuid
  END
  AND CASE
    WHEN $2::text IS NULL THEN TRUE
    WHEN $2::text = '' THEN TRUE
    ELSE name = $2::text
  END
`

type GetOrderStatusParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetOrderStatus(ctx context.Context, arg GetOrderStatusParams) (OrderStatus, error) {
	row := q.db.QueryRow(ctx, getOrderStatus, arg.ID, arg.Name)
	var i OrderStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

type InsertTempTableOrderItemsParams struct {
	ID       uuid.UUID
	Quantity int32
	OrderID  uuid.UUID
	Price    pgtype.Numeric
	BookID   uuid.UUID
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT
  id, quantity, order_id, price, book_id
FROM
  order_items
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid IS NULL THEN TRUE
    WHEN $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE order_id = $2::uuid
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    WHEN cardinality($3::uuid[]) = 0 THEN TRUE
    ELSE order_id = ANY ($3::uuid[])
  END
ORDER BY
  id
`

type ListOrderItemsParams struct {
	IDs      []uuid.UUID
	OrderID  uuid.UUID
	OrderIDs []uuid.UUID
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.IDs, arg.OrderID, arg.OrderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.OrderID,
			&i.Price,
			&i.BookID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatuses = `-- name: ListOrderStatuses :many
SELECT
  id, name
FROM
  order_statuses
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
ORDER BY
  id ASC
`

type ListOrderStatusesParams struct {
	IDs []uuid.UUID
}

func (q *Queries) ListOrderStatuses(ctx context.Context, arg ListOrderStatusesParams) ([]OrderStatus, error) {
	rows, err := q.db.Query(ctx, listOrderStatuses, arg.IDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatus
	for rows.Next() {
		var i OrderStatus
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
  id, address, city, created_at, updated_at, total_amount, is_paid, user_id, status_id, provider_id
FROM
  orders
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid IS NULL THEN TRUE
    WHEN $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE user_id = $2::uuid
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    WHEN cardinality($3::uuid[]) = 0 THEN TRUE
    ELSE user_id = ANY ($3::uuid[])
  END
  AND CASE
    WHEN $4::uuid IS NULL THEN TRUE
    WHEN $4::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN TRUE
    ELSE status_id = $4::uuid
  END
  AND CASE
    WHEN $5::uuid[] IS NULL THEN TRUE
    WHEN cardinality($5::uuid[]) = 0 THEN TRUE
    ELSE status_id = ANY ($5::uuid[])
  END
ORDER BY
  id ASC
OFFSET $6::integer
LIMIT NULLIF($7::integer, 0)
`

type ListOrdersParams struct {
	IDs       []uuid.UUID
	UserID    uuid.UUID
	UserIDs   []uuid.UUID
	StatusID  uuid.UUID
	StatusIDs []uuid.UUID
	Offset    int32
	Limit     int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.IDs,
		arg.UserID,
		arg.UserIDs,
		arg.StatusID,
		arg.StatusIDs,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.City,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalAmount,
			&i.IsPaid,
			&i.UserID,
			&i.StatusID,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeOrderItemsFromTemp = `-- name: MergeOrderItemsFromTemp :exec
MERGE INTO order_items AS target
USING temp_order_items AS source
  ON target.id = source.id
WHEN MATCHED THEN
  UPDATE SET
    quantity = source.quantity,
    order_id = source.order_id,
    price = source.price,
    book_id = source.book_id
WHEN NOT MATCHED THEN
  INSERT (
    id,
    quantity,
    order_id,
    price,
    book_id
  )
  VALUES (
    source.id,
    source.quantity,
    source.order_id,
    source.price,
    source.book_id
  )
WHEN NOT MATCHED BY SOURCE
  AND target.order_id IN (SELECT DISTINCT order_id FROM temp_order_items) THEN
  DELETE
`

func (q *Queries) MergeOrderItemsFromTemp(ctx context.Context) error {
	_, err := q.db.Exec(ctx, mergeOrderItemsFromTemp)
	return err
}

const upsertOrder = `-- name: UpsertOrder :exec
INSERT INTO orders (
  id,
  user_id,
  address,
  city,
  total_amount,
  is_paid,
  provider_id,
  status_id,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  total_amount = EXCLUDED.total_amount,
  is_paid = EXCLUDED.is_paid,
  provider_id = EXCLUDED.provider_id,
  status_id = EXCLUDED.status_id,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at
`

type UpsertOrderParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Address     string
	City        string
	TotalAmount pgtype.Numeric
	IsPaid      bool
	ProviderID  uuid.UUID
	StatusID    uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOrder,
		arg.ID,
		arg.UserID,
		arg.Address,
		arg.City,
		arg.TotalAmount,
		arg.IsPaid,
		arg.ProviderID,
		arg.StatusID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
