// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error)
	CountBooks(ctx context.Context, arg CountBooksParams) (int64, error)
	CountCategories(ctx context.Context, arg CountCategoriesParams) (int64, error)
	CountMedium(ctx context.Context, arg CountMediumParams) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error)
	CreateTempTableBooksCategories(ctx context.Context) error
	CreateTempTableBooksMedia(ctx context.Context) error
	CreateTempTableCartItems(ctx context.Context) error
	CreateTempTableOrderItems(ctx context.Context) error
	GetArticle(ctx context.Context, arg GetArticleParams) (Article, error)
	GetBook(ctx context.Context, arg GetBookParams) (Book, error)
	GetCart(ctx context.Context, arg GetCartParams) (Cart, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetMedia(ctx context.Context, arg GetMediaParams) (Medium, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetOrderItem(ctx context.Context, arg GetOrderItemParams) (OrderItem, error)
	GetOrderProvider(ctx context.Context, arg GetOrderProviderParams) (OrderProvider, error)
	GetOrderStatus(ctx context.Context, arg GetOrderStatusParams) (OrderStatus, error)
	GetReview(ctx context.Context, arg GetReviewParams) (Review, error)
	InsertTempTableBooksCategories(ctx context.Context, arg []InsertTempTableBooksCategoriesParams) (int64, error)
	InsertTempTableBooksMedia(ctx context.Context, arg []InsertTempTableBooksMediaParams) (int64, error)
	InsertTempTableCartItems(ctx context.Context, arg []InsertTempTableCartItemsParams) (int64, error)
	InsertTempTableOrderItems(ctx context.Context, arg []InsertTempTableOrderItemsParams) (int64, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	ListBooksCategories(ctx context.Context, arg ListBooksCategoriesParams) ([]BooksCategory, error)
	ListBooksMedia(ctx context.Context, arg ListBooksMediaParams) ([]BooksMedium, error)
	ListCartItems(ctx context.Context, arg ListCartItemsParams) ([]CartItem, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListMedium(ctx context.Context, arg ListMediumParams) ([]Medium, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListOrderStatuses(ctx context.Context, arg ListOrderStatusesParams) ([]OrderStatus, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListReviewVotes(ctx context.Context, arg ListReviewVotesParams) ([]ReviewVote, error)
	ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error)
	MergeBooksCategoriesFromTemp(ctx context.Context) error
	MergeBooksMediaFromTemp(ctx context.Context) error
	MergeCartItemsFromTemp(ctx context.Context) error
	MergeOrderItemsFromTemp(ctx context.Context) error
	UpsertArticle(ctx context.Context, arg UpsertArticleParams) error
	UpsertBook(ctx context.Context, arg UpsertBookParams) error
	UpsertCart(ctx context.Context, arg UpsertCartParams) error
	UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error
	UpsertMedia(ctx context.Context, arg UpsertMediaParams) error
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) error
	UpsertReview(ctx context.Context, arg UpsertReviewParams) error
	UpsertReviewVote(ctx context.Context, arg UpsertReviewVoteParams) error
}

var _ Querier = (*Queries)(nil)
