// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReviews = `-- name: CountReviews :one
SELECT
  COUNT(*) AS count
FROM
  reviews
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE reviews.id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    WHEN cardinality($2::uuid[]) = 0 THEN TRUE
    ELSE reviews.book_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    WHEN cardinality($3::uuid[]) = 0 THEN TRUE
    ELSE reviews.user_id = ANY ($3::uuid[])
  END
  AND CASE
    WHEN $4::text = 'exclude' THEN reviews.deleted_at IS NULL
    WHEN $4::text = 'only' THEN reviews.deleted_at IS NOT NULL
    WHEN $4::text = 'all' THEN TRUE
    ELSE reviews.deleted_at IS NULL
  END
`

type CountReviewsParams struct {
	IDs     []uuid.UUID
	BookIDs []uuid.UUID
	UserIDs []uuid.UUID
	Deleted string
}

func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews,
		arg.IDs,
		arg.BookIDs,
		arg.UserIDs,
		arg.Deleted,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReview = `-- name: GetReview :one
SELECT
  id, rating, vote_count, content, user_id, book_id, created_at, updated_at, deleted_at
FROM
  reviews
WHERE
  id = $1
  AND CASE
    WHEN $2::text = 'exclude' THEN deleted_at IS NULL
    WHEN $2::text = 'only' THEN deleted_at IS NOT NULL
    WHEN $2::text = 'all' THEN TRUE
    ELSE deleted_at IS NULL
  END
`

type GetReviewParams struct {
	ID      uuid.UUID
	Deleted string
}

func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, arg.ID, arg.Deleted)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.VoteCount,
		&i.Content,
		&i.UserID,
		&i.BookID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReviewVotes = `-- name: ListReviewVotes :many
SELECT
  id, user_id, review_id, is_up, created_at
FROM
  review_votes
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE review_id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    WHEN cardinality($2::uuid[]) = 0 THEN TRUE
    ELSE user_id = ANY ($2::uuid[])
  END
ORDER BY
  created_at DESC
`

type ListReviewVotesParams struct {
	ReviewIds []uuid.UUID
	UserIDs   []uuid.UUID
}

func (q *Queries) ListReviewVotes(ctx context.Context, arg ListReviewVotesParams) ([]ReviewVote, error) {
	rows, err := q.db.Query(ctx, listReviewVotes, arg.ReviewIds, arg.UserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVote
	for rows.Next() {
		var i ReviewVote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReviewID,
			&i.IsUp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT
  reviews.id, reviews.rating, reviews.vote_count, reviews.content, reviews.user_id, reviews.book_id, reviews.created_at, reviews.updated_at, reviews.deleted_at
FROM
  reviews
WHERE
  CASE
    WHEN $1::uuid[] IS NULL THEN TRUE
    WHEN cardinality($1::uuid[]) = 0 THEN TRUE
    ELSE reviews.id = ANY ($1::uuid[])
  END
  AND CASE
    WHEN $2::uuid[] IS NULL THEN TRUE
    WHEN cardinality($2::uuid[]) = 0 THEN TRUE
    ELSE reviews.book_id = ANY ($2::uuid[])
  END
  AND CASE
    WHEN $3::uuid[] IS NULL THEN TRUE
    WHEN cardinality($3::uuid[]) = 0 THEN TRUE
    ELSE reviews.user_id = ANY ($3::uuid[])
  END
  AND CASE
    WHEN $4::text = 'exclude' THEN reviews.deleted_at IS NULL
    WHEN $4::text = 'only' THEN reviews.deleted_at IS NOT NULL
    WHEN $4::text = 'all' THEN TRUE
    ELSE reviews.deleted_at IS NULL
  END
ORDER BY
  reviews.created_at DESC
OFFSET $5::integer
LIMIT NULLIF($6::integer, 0)
`

type ListReviewsParams struct {
	IDs     []uuid.UUID
	BookIDs []uuid.UUID
	UserIDs []uuid.UUID
	Deleted string
	Offset  int32
	Limit   int32
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews,
		arg.IDs,
		arg.BookIDs,
		arg.UserIDs,
		arg.Deleted,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.VoteCount,
			&i.Content,
			&i.UserID,
			&i.BookID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :exec
INSERT INTO reviews (
  id,
  rating,
  vote_count,
  content,
  user_id,
  book_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  NULLIF($9::timestamptz, '0001-01-01T00:00:00Z'::timestamptz)
)
ON CONFLICT (id) DO UPDATE SET
  rating = EXCLUDED.rating,
  vote_count = EXCLUDED.vote_count,
  content = EXCLUDED.content,
  user_id = EXCLUDED.user_id,
  book_id = EXCLUDED.book_id,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at,
  deleted_at = COALESCE(EXCLUDED.deleted_at, reviews.deleted_at)
`

type UpsertReviewParams struct {
	ID        uuid.UUID
	Rating    int16
	VoteCount int32
	Content   *string
	UserID    uuid.UUID
	BookID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) error {
	_, err := q.db.Exec(ctx, upsertReview,
		arg.ID,
		arg.Rating,
		arg.VoteCount,
		arg.Content,
		arg.UserID,
		arg.BookID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertReviewVote = `-- name: UpsertReviewVote :exec
INSERT INTO review_votes (
  id,
  user_id,
  review_id,
  is_up,
  created_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  review_id = EXCLUDED.review_id,
  is_up = EXCLUDED.is_up,
  created_at = EXCLUDED.created_at
`

type UpsertReviewVoteParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ReviewID  uuid.UUID
	IsUp      bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertReviewVote(ctx context.Context, arg UpsertReviewVoteParams) error {
	_, err := q.db.Exec(ctx, upsertReviewVote,
		arg.ID,
		arg.UserID,
		arg.ReviewID,
		arg.IsUp,
		arg.CreatedAt,
	)
	return err
}
