// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "Get all books with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "List all books",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "name": "category_ids",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "publisher",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "name": "sort_price",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "name": "sort_recent",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginationResponseDTO-internal_delivery_http_BookResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Create a new book",
                "parameters": [
                    {
                        "description": "Book request",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateBookData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/BookResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "Get book details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Get book by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BookResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete book by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Delete book",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update book details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Update book",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update book request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateBookData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BookResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Create a new cart",
                "parameters": [
                    {
                        "description": "Cart request",
                        "name": "cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateCartData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart/me": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get cart details for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get current user's cart",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart/user/{user_id}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get cart details by user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get cart by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get cart details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get cart by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart/{id}/items": {
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Add a new item to the cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add item to cart",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cart item request",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateCartItemData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/cart/{id}/items/{item_id}": {
            "delete": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Remove item from cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Delete cart item",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update cart item quantity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Update cart item",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update cart item request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateCartItemData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CartResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Get all categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "List all categories",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginationResponseDTO-internal_delivery_http_CategoryResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": "Category request",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateCategoryRequestData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/CategoryResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "delete": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Delete category",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update category details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Update category",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update category request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateCategoryRequestData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CategoryResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/categories/{slug}": {
            "get": {
                "description": "Get category details by Slug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get category by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CategoryResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/media": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get all media with optional search",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "List all media",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PaginationResponseDTO-internal_delivery_http_MediaResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new media",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Create a new media",
                "parameters": [
                    {
                        "description": "Media request",
                        "name": "media",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateMediaRequestData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/MediaResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/media/images/upload-url": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get a presigned URL to upload media images",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get presigned URL for image upload",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UploadImageURLResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/media/images/{image_id}/delete-url": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get a presigned URL to delete media images",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get presigned URL for image deletion",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Media Image ID",
                        "name": "image_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DeleteImageURLResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/media/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get media details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get media by ID",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MediaResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete media by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Delete media",
                "parameters": [
                    {
                        "type": "string",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get all orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List all orders",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "Pending",
                            "Processing",
                            "Shipping",
                            "Delivered",
                            "Cancelled"
                        ],
                        "type": "string",
                        "x-enum-varnames": [
                            "OrderStatusPending",
                            "OrderStatusProcessing",
                            "OrderStatusShipping",
                            "OrderStatusDelivered",
                            "OrderStatusCancelled"
                        ],
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/OrderResponseDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order request",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateOrderData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/OrderResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/orders/vnpay/ipn": {
            "get": {
                "description": "Verify VNPay IPN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Verify VNPay IPN",
                "parameters": [
                    {
                        "type": "string",
                        "name": "vnp_Amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_BankCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_BankTranNo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_CardType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_OrderInfo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_PayDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_ResponseCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_SecureHash",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_TmnCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_TransactionNo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_TransactionStatus",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "vnp_TxnRef",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VerifyVNPayIPNResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get order details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Get order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/OrderResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "OAuth2AccessCode": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update  order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Update order",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update order status request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateOrderData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/OrderResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BookCategoryResponseDTO": {
            "type": "object",
            "required": [
                "id",
                "name",
                "slug"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "BookMediaResponseDTO": {
            "type": "object",
            "required": [
                "id",
                "isCover",
                "order",
                "url"
            ],
            "properties": {
                "altText": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isCover": {
                    "type": "boolean"
                },
                "order": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "BookResponseDTO": {
            "type": "object",
            "required": [
                "author",
                "categories",
                "createdAt",
                "id",
                "media",
                "pagesCount",
                "price",
                "publisher",
                "purchaseCount",
                "rating",
                "stockQuantity",
                "title",
                "updatedAt",
                "yearPublished"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/BookCategoryResponseDTO"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/BookMediaResponseDTO"
                    }
                },
                "pagesCount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "purchaseCount": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "yearPublished": {
                    "type": "integer"
                }
            }
        },
        "CartItemBookMediaResponseDTO": {
            "type": "object",
            "required": [
                "id",
                "isCover",
                "order",
                "url"
            ],
            "properties": {
                "altText": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isCover": {
                    "type": "boolean"
                },
                "order": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "CartItemBookResponseDTO": {
            "type": "object",
            "required": [
                "author",
                "id",
                "medium",
                "pagesCount",
                "price",
                "publisher",
                "purchaseCount",
                "rating",
                "stockQuantity",
                "title",
                "yearPublished"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "medium": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CartItemBookMediaResponseDTO"
                    }
                },
                "pagesCount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "purchaseCount": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "yearPublished": {
                    "type": "integer"
                }
            }
        },
        "CartItemResponseDTO": {
            "type": "object",
            "required": [
                "book",
                "id",
                "quantity"
            ],
            "properties": {
                "book": {
                    "$ref": "#/definitions/CartItemBookResponseDTO"
                },
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "CartResponseDTO": {
            "type": "object",
            "required": [
                "id",
                "items",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CartItemResponseDTO"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "CategoryResponseDTO": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "name",
                "slug",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "CreateBookData": {
            "type": "object",
            "required": [
                "author",
                "categoryIds",
                "media",
                "pagesCount",
                "price",
                "publisher",
                "stockQuantity",
                "title",
                "yearPublished"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "categoryIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CreateBookMediaData"
                    }
                },
                "pagesCount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "yearPublished": {
                    "type": "integer"
                }
            }
        },
        "CreateBookMediaData": {
            "type": "object",
            "required": [
                "isCover",
                "mediaId"
            ],
            "properties": {
                "isCover": {
                    "type": "boolean"
                },
                "mediaId": {
                    "type": "string"
                }
            }
        },
        "CreateCartData": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "CreateCartItemData": {
            "type": "object",
            "required": [
                "bookId",
                "quantity"
            ],
            "properties": {
                "bookId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "CreateCategoryRequestData": {
            "type": "object",
            "required": [
                "name",
                "slug"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "CreateMediaRequestData": {
            "type": "object",
            "required": [
                "key",
                "order"
            ],
            "properties": {
                "altText": {
                    "type": "string",
                    "maxLength": 200
                },
                "key": {
                    "type": "string"
                },
                "order": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "CreateOrderData": {
            "type": "object",
            "required": [
                "address",
                "city",
                "email",
                "firstName",
                "lastName",
                "phone",
                "provider",
                "userId"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/OrderProvider"
                },
                "returnUrl": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "DeleteImageURLResponseDTO": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "MediaResponseDTO": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "order",
                "url"
            ],
            "properties": {
                "altText": {
                    "type": "string",
                    "maxLength": 200
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order": {
                    "type": "integer",
                    "minimum": 0
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "OrderItemBookResponseDTO": {
            "type": "object",
            "required": [
                "author",
                "id",
                "price",
                "rating",
                "stockQuantity",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "OrderItemResponseDTO": {
            "type": "object",
            "required": [
                "book",
                "id",
                "price",
                "quantity"
            ],
            "properties": {
                "book": {
                    "$ref": "#/definitions/OrderItemBookResponseDTO"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "OrderProvider": {
            "type": "string",
            "enum": [
                "COD",
                "VNPAY",
                "MOMO",
                "ZALOPAY"
            ],
            "x-enum-varnames": [
                "PaymentProviderCOD",
                "PaymentProviderVNPAY",
                "PaymentProviderMOMO",
                "PaymentProviderZALOPAY"
            ]
        },
        "OrderResponseDTO": {
            "type": "object",
            "required": [
                "address",
                "city",
                "createdAt",
                "email",
                "firstName",
                "id",
                "isPaid",
                "items",
                "lastName",
                "phone",
                "provider",
                "status",
                "totalAmount",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isPaid": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderItemResponseDTO"
                    }
                },
                "lastName": {
                    "type": "string"
                },
                "paymentUrl": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/OrderProvider"
                },
                "status": {
                    "$ref": "#/definitions/OrderStatus"
                },
                "totalAmount": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "OrderStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Processing",
                "Shipping",
                "Delivered",
                "Cancelled"
            ],
            "x-enum-varnames": [
                "OrderStatusPending",
                "OrderStatusProcessing",
                "OrderStatusShipping",
                "OrderStatusDelivered",
                "OrderStatusCancelled"
            ]
        },
        "PaginationMetaResponseDTO": {
            "type": "object",
            "required": [
                "currentPage",
                "itemsPerPage",
                "totalItems",
                "totalPages"
            ],
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "itemsPerPage": {
                    "type": "integer"
                },
                "pageItems": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "PaginationResponseDTO-internal_delivery_http_BookResponseDTO": {
            "type": "object",
            "required": [
                "data",
                "meta"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/BookResponseDTO"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/PaginationMetaResponseDTO"
                }
            }
        },
        "PaginationResponseDTO-internal_delivery_http_CategoryResponseDTO": {
            "type": "object",
            "required": [
                "data",
                "meta"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CategoryResponseDTO"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/PaginationMetaResponseDTO"
                }
            }
        },
        "PaginationResponseDTO-internal_delivery_http_MediaResponseDTO": {
            "type": "object",
            "required": [
                "data",
                "meta"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MediaResponseDTO"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/PaginationMetaResponseDTO"
                }
            }
        },
        "UpdateBookData": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "categoryIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UpdateBookMediaData"
                    }
                },
                "pagesCount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "publisher": {
                    "type": "string"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "yearPublished": {
                    "type": "integer"
                }
            }
        },
        "UpdateBookMediaData": {
            "type": "object",
            "required": [
                "isCover",
                "mediaId"
            ],
            "properties": {
                "isCover": {
                    "type": "boolean"
                },
                "mediaId": {
                    "type": "string"
                }
            }
        },
        "UpdateCartItemData": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "UpdateCategoryRequestData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "UpdateOrderData": {
            "type": "object",
            "required": [
                "address",
                "isPaid",
                "status"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "isPaid": {
                    "type": "boolean"
                },
                "status": {
                    "$ref": "#/definitions/OrderStatus"
                }
            }
        },
        "UploadImageURLResponseDTO": {
            "type": "object",
            "required": [
                "key",
                "url"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "VerifyVNPayIPNResponseDTO": {
            "type": "object",
            "required": [
                "Message",
                "RspCode"
            ],
            "properties": {
                "Message": {
                    "type": "string"
                },
                "RspCode": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2AccessCode": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "/auth/protocol/openid-connect/auth",
            "tokenUrl": "/auth/protocol/openid-connect/token",
            "scopes": {
                "address": "Grants read access to address",
                "phone": "Grants read access to phone number"
            }
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/auth/protocol/openid-connect/token",
            "scopes": {
                "address": "Grants read access to address",
                "phone": "Grants read access to phone number"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
